name: CLA Check

on:
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check CLA
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const script = fs.readFileSync('.github/cla/cla-check.js', 'utf8');
            const runScript = async () => {
              try {
                await eval(script);
              } catch (error) {
                console.error('Error running CLA check:', error);
                core.setFailed(error.message);
              }
            };
            await runScript();
