name: CLA Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check CLA
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const script = fs.readFileSync('.github/cla/cla-check.js', 'utf8');
            eval(script);
