name: CLA Assistant

on:
  pull_request:
    types: [
      opened,
      synchronize,
      reopened,
      closed,
      labeled,
      unlabeled,
      assigned,
      unassigned,
      review_requested,
      review_request_removed,
      ready_for_review,
      converted_to_draft,
      auto_merge_enabled,
      auto_merge_disabled
    ]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CLA Assistant
        uses: cla-assistant/github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
          CONFIG_FILE: .cla-assistant.yml 
