name: Setup Labels

on:
  workflow_dispatch:  # Allows manual triggering
  repository_dispatch:
    types: [setup_labels]

jobs:
  setup-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CLA Label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'cla-signed',
                color: '00ff00',  // Green
                description: 'Pull request author has signed the CLA'
              });
              console.log('CLA label created successfully');
            } catch (error) {
              if (error.status === 422) {
                console.log('CLA label already exists');
              } else {
                throw error;
              }
            }
